USE [master]
GO

/****** Object:  Database [SQLKWSALESDB]    Script Date: 2023/09/06 09:36:34 ******/
CREATE DATABASE [SQLKWSALESDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
 --The path below can be altered to location of choice
( NAME = N'SqlKWSales', FILENAME = N'C:\VCSDB\SQLKWSALESDB.mdf' , SIZE = 14528KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SqlKWSales_log', FILENAME = N'C:\VCSDB\SQLKWSALESDB.MDF_log.ldf' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SQLKWSALESDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SQLKWSALESDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SQLKWSALESDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SQLKWSALESDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SQLKWSALESDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SQLKWSALESDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SQLKWSALESDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SQLKWSALESDB] SET  MULTI_USER 
GO

ALTER DATABASE [SQLKWSALESDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SQLKWSALESDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SQLKWSALESDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SQLKWSALESDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SQLKWSALESDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SQLKWSALESDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SQLKWSALESDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SQLKWSALESDB] SET  READ_WRITE 
GO

--**************************************************************************************************************
--Create Tables
USE SQLKWSALESDB
GO

--Customers
CREATE TABLE dbo.Customers
(
	CustomerID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Address NVARCHAR(100) NOT NULL,
	City NVARCHAR(40) NOT NULL,
	State NVARCHAR(30) NOT NULL,
	Zip NVARCHAR(10) NOT NULL
);
GO

--Non Unique, Non clustered
CREATE INDEX IX_Customers_LastName
ON dbo.Customers (LastName ASC);
GO

CREATE TABLE dbo.Orders
(
	OrderID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	CustomerID INT NOT NULL,
	OrderDate DATETIME NOT NULL,
	CONSTRAINT FK_Orders_Customers_CustomerID FOREIGN KEY(CustomerID) REFERENCES Customers(CustomerID)
);
GO

CREATE TABLE dbo.Products
(
	ProductID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	[Description] NVARCHAR(50) NOT NULL,
	Price MONEY NOT NULL,
	NumberSold INT NOT NULL
);
GO

ALTER TABLE dbo.Products
ADD CONSTRAINT DF_Products_Price DEFAULT(0) FOR Price;
GO
ALTER TABLE dbo.Products
Add CONSTRAINT DF_Products_NumberSold DEFAULT(0) FOR NumberSold;

CREATE TABLE dbo.Purchases
(
	OrderID INT NOT NULL,
	ProductID INT NOT NULL,
	Quantity INT NOT NULL,
	CONSTRAINT PK_Purchases_OrderID_ProductID PRIMARY KEY(OrderID, ProductID),
	CONSTRAINT FK_Purchases_Orders_OrderID FOREIGN KEY(OrderID) REFERENCES Orders(OrderID),
	CONSTRAINT FK_Purchases_Products_ProductID FOREIGN KEY(ProductID) REFERENCES Products(ProductID)
);
GO

